version: '3.4'

services:
  forums:
    build:
      context: .
      dockerfile: Forums/Dockerfile
    ports:
    - 5000:80
    depends_on:
    - db


  # MySQL database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - "1434:1433"
    environment:
      MSSQL_SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"
